### ISSUE TITLE
e questions about MMNet: A Model-based Multimodal Network for Human Action Recognition in RGB-D Videos 

### ISSUE THREAD

**Issue by ch1998** [bruceyo/MMNet#1]
Dear author, I have some questions about your paper MMNet: A Model-based Multimodal Network for Human Action Recognition in RGB-D Videos.
I use the code you posted in github, but how did some of the files get there? 
E.g data/ntu_st_gcn/xsub/val_label.pkl .The file has and differs from the pkl of the test data.

I followed the code you posted on github to retrain to get a new pkl file, and when using the ensemble file to augment the results, yielded extremely low results. I put the result in the image below:
How do I get the results in your essay?
![image1](https://user-images.githubusercontent.com/37291486/180429661-a465083b-677c-45ae-836b-42a7d61df9f6.png)
![image2](https://user-images.githubusercontent.com/37291486/180429685-b123a514-9705-4733-85b2-c2fa7cc85480.png)

**Comment by bruceyo** [comment]
Hi there, thank you for the interest!

Different skeleton-based models such as ST-GCN, 2s-AGCN, and MS-G3D might have no consistent evaluation sequence in their `val_label.pkl` files. Hence, please pay attention to Lines 49-61 of [ensemble code](https://github.com/bruceyo/MMNet/blob/main/ensemble/ensemble_ntu60.py) and adjust it accordingly to make their label sequence consistent to get proper results.

**Comment by ch1998** [comment]
Thank you very much for your reply, I will try it

> 您好，感谢您的关注！
> 
> 不同的基于骨架的模型（例如 ST-GCN、2s-AGCN 和 MS-G3D）在其`val_label.pkl`文件中可能没有一致的评估顺序。因此，请注意[ensemble 代码](https://github.com/bruceyo/MMNet/blob/main/ensemble/ensemble_ntu60.py)的第 49-61 行，并进行相应的调整，使其标签序列一致，以获得正确的结果。

Thank you very much for your reply, I will try it

**Comment by ch1998** [comment]
> Hi there, thank you for the interest!
> 
> Different skeleton-based models such as ST-GCN, 2s-AGCN, and MS-G3D might have no consistent evaluation sequence in their `val_label.pkl` files. Hence, please pay attention to Lines 49-61 of [ensemble code](https://github.com/bruceyo/MMNet/blob/main/ensemble/ensemble_ntu60.py) and adjust it accordingly to make their label sequence consistent to get proper results.

Hi, thanks again for your work.
I adjusted the val_label.pkl file as you described, and got the correct accuracy on both joint and bone, but when I train main_rgd_fuse, the accuracy is very low,
Start command: python main_rgb_fused.py recognition -c config/ntu60_xsub/train_rgb_fused.yaml

![image3](https://user-images.githubusercontent.com/37291486/180680163-cd02af63-d52a-4227-b342-233823b4db11.png)

yaml file： 
![image](https://user-images.githubusercontent.com/37291486/180680234-fb5f7b88-4f64-450a-968c-6f726b1ba8c7.png)
![image](https://user-images.githubusercontent.com/37291486/180680290-1fd04247-23d3-4c90-bf90-8ed888669ac4.png)

How should I tune to get the correct rgb_fused accuracy？

**Comment by Mcudll929** [comment]
> > Hi there, thank you for the interest!
> > Different skeleton-based models such as ST-GCN, 2s-AGCN, and MS-G3D might have no consistent evaluation sequence in their `val_label.pkl` files. Hence, please pay attention to Lines 49-61 of [ensemble code](https://github.com/bruceyo/MMNet/blob/main/ensemble/ensemble_ntu60.py) and adjust it accordingly to make their label sequence consistent to get proper results.
> 
> Hi, thanks again for your work. I adjusted the val_label.pkl file as you described, and got the correct accuracy on both joint and bone, but when I train main_rgd_fuse, the accuracy is very low, Start command: python main_rgb_fused.py recognition -c config/ntu60_xsub/train_rgb_fused.yaml
> 
> ![image3](https://user-images.githubusercontent.com/37291486/180680163-cd02af63-d52a-4227-b342-233823b4db11.png)
> 
> yaml file： ![image](https://user-images.githubusercontent.com/37291486/180680234-fb5f7b88-4f64-450a-968c-6f726b1ba8c7.png) ![image](https://user-images.githubusercontent.com/37291486/180680290-1fd04247-23d3-4c90-bf90-8ed888669ac4.png)
> 
> How should I tune to get the correct rgb_fused accuracy？

Hi,I had the same problem when running the code.
Did u solve the relevant problem after that?

**Comment by ch1998** [comment]
> > > Hi there, thank you for the interest!
> > > Different skeleton-based models such as ST-GCN, 2s-AGCN, and MS-G3D might have no consistent evaluation sequence in their `val_label.pkl` files. Hence, please pay attention to Lines 49-61 of [ensemble code](https://github.com/bruceyo/MMNet/blob/main/ensemble/ensemble_ntu60.py) and adjust it accordingly to make their label sequence consistent to get proper results.
> > 
> > 
> > Hi, thanks again for your work. I adjusted the val_label.pkl file as you described, and got the correct accuracy on both joint and bone, but when I train main_rgd_fuse, the accuracy is very low, Start command: python main_rgb_fused.py recognition -c config/ntu60_xsub/train_rgb_fused.yaml
> > ![image3](https://user-images.githubusercontent.com/37291486/180680163-cd02af63-d52a-4227-b342-233823b4db11.png)
> > yaml file： ![image](https://user-images.githubusercontent.com/37291486/180680234-fb5f7b88-4f64-450a-968c-6f726b1ba8c7.png) ![image](https://user-images.githubusercontent.com/37291486/180680290-1fd04247-23d3-4c90-bf90-8ed888669ac4.png)
> > How should I tune to get the correct rgb_fused accuracy？
> 
> Hi,I had the same problem when running the code. Did u solve the relevant problem after that?

I'm sorry, I didn't solve this problem
