### ISSUE TITLE
Masked depth maps

### ISSUE THREAD

**Issue by sunbeam-kkt** [bruceyo/MMNet#19]
Excuse me, in the feeder/segment_rgbbody_ntu.py, what files are placed in the depth_path?

**Comment by sunbeam-kkt** [comment]
Why need the Masked Depth Maps? Is it necessary to reduce the interference of chaotic backgrounds in RGB images?

**Comment by bruceyo** [comment]
> Why need the Masked Depth Maps? Is it necessary to reduce the interference of chaotic backgrounds in RGB images?

Yes, this is part of the preprocessing step not reported in the main paper. It can gain slight improvements for cases that have irrelevant subjects.
