### ISSUE TITLE
Training RGB video (ntu60)

### ISSUE THREAD

**Issue by zihos** [bruceyo/MMNet#3]
Hello, I'm trying to train RGB video using 'fivevs' you provided through Google Drive.
I changed the path of the rgb_path_ntu60 in the feeder_rgb_fuesed_ntu.py.
Also, I changed the data and label path in the train_rgb_fused.yaml.
Then, I ran 
```
python main_rgb_fused.py recognition -c config/ntu60_xsub/train_rgb_fused.yaml
```

However, there was an error related to the input shape.
Could you let me know how to train RGB video?
Where should I have to change the code?
The screenshot of the error is
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/46514182/192124344-637c3074-561b-40e9-975c-f35873e1a826.png">

I'm looking forward to your reply!
Thank you :)

**Comment by bruceyo** [comment]
The function in `MMnet/net/gcn.py` is to extract the joint weight feature from the GCN model. 
You might have not loaded the correct pre-trained GCN model of the skeleton modality. 

Anyways, the information is not sufficient for tracing or reproducing the problem. You should provide more information such as how is your `train_rgb_fused.yaml` looks like.

**Comment by zihos** [comment]
I changed `skeleton_joints_pkl: results/ntu60/xsub/joint_result_msg3d.pkl` to `skeleton_joints_pkl: results/ntu60/xsub/joint_result_stgcn.pkl` , but still same error occurs.. T^T
Here's my `train_rgb_fused.yaml` file
```
# python main_rgb_fused.py recognition -c config/ntu60_xsub/train_rgb_fused.yaml
work_dir: ../../data/st-gcn/xsub/with_rgb/rgb_tp15_tf5_

skeleton_joints_pkl: results/ntu60/xsub/joint_result_msg3d.pkl
skeleton_bones_pkl: results/ntu60/xsub/bone_result_msg3d.pkl

# feeder
feeder: feeder.feeder_rgb_fused_ntu.Feeder
train_feeder_args:
  debug: False
  random_choose: False
  centralization: False
  random_move: False
  window_size: -1
  random_flip: False
  random_interval: True
  temporal_rgb_frames: 5
  data_path: /home/Data/MMNet/ntu60_skeletons_preprocessed/xsub/train_data_joint.npy
  label_path: /home/Data/MMNet/ntu60_skeletons_preprocessed/xsub/train_label.pkl
test_feeder_args:
  debug: False
  centralization: False
  evaluation: True
  temporal_rgb_frames: 5
  data_path: /home/Data/MMNet/ntu60_skeletons_preprocessed/xsub/val_data_joint.npy
  label_path: /home/Data/MMNet/ntu60_skeletons_preprocessed/xsub/val_label.pkl

# model
model: net.mmn.Model
model_args:
  in_channels: 3
  num_class: 60
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

# training
temporal_positions: 15
fix_weights: True
joint_weights: models/ntu60/xsub/joint_model_stgcn.pt
device: [0,1,2,3]
weight_decay: 0.0001
base_lr: 0.1
step: [10, 50]
batch_size: 64
test_batch_size: 64
num_epoch: 80

# debug
debug: False
```
Could you check the wrong point? 
If you need more information, please let me know :)
Thank you!

**Comment by bruceyo** [comment]
What is your `MMnet/net/gcn.py` looks like? 
Are there any other changes to the code?

To make the code run, you can comment out Line 113 and change Line 116 from `return output, feature` to `return feature` in the file `MMnet/net/gcn.py`.
Then change Line 45 from ` predict, feature = self.stgcn.extract_feature(x_)` to ` feature = self.stgcn.extract_feature(x_)` in file [mmn.py](https://github.com/bruceyo/MMNet/blob/main/net/mmn.py).

**Comment by katahiyu** [comment]
> 
Where did you save 'fivefs' saved from google drive?

**Comment by bruceyo** [comment]
> > 
> 
> Where did you save 'fivefs' saved from google drive?

You can generate them via:
`python tools/data_gen/gen_fivefs_<dataset>`
  Only the NTU-RGB+D and PKU-MMD are provided (please refer to the [README.md](https://github.com/bruceyo/MMNet#readme))

**Comment by katahiyu** [comment]
Thanks for your reply.
The file gen_fivefs_<dataset> does not exist in the specified directory. What should I do?
Also, if I download the processed data from GoogleDrive, in which directory is the proper place to place it?
![image](https://user-images.githubusercontent.com/114911420/194566356-e6773ab6-2c10-44cc-bf50-dac58df2bd1d.png)

**Comment by zihos** [comment]
@bruceyo 
Thank you for reply :)
I didn't change the code except for the data_path, and here's my `gcn.py` below.

I changed the code that you commented and training is working well before epoch 5,
but there's another error when printing the eval top 1.
Here's my error below
```
Traceback (most recent call last):
  File "main_rgb_fused.py", line 33, in <module>
    p.start()
  File "/home/zio/mocap/MMNet/processor/processor.py", line 127, in start
    self.test()
  File "/home/zio/mocap/MMNet/processor/recognition_rgb_fused.py", line 239, in test
    self.show_topk(k, 'eval')
  File "/home/zio/mocap/MMNet/processor/recognition_rgb_fused.py", line 121, in show_topk
    _, r11_yan = r1_yan[i]
IndexError: list index out of range
```
I don't know why the index error occurs.
Could you let me know if you know the reason?

**Comment by zihos** [comment]
Dear author,
Hello, I checked why the index out of range error happens
and i found that the length of `self.label` is 16560, but the length of the `r1_yan` is 16487

this is the error below
```
[10.11.22|08:41:12]     ls_cls: 4.508251852050251
[10.11.22|08:41:12]     Top1: 3.87%
r1_yan 16487
label:  16560
Traceback (most recent call last):
  File "main_rgb_fused.py", line 33, in <module>
    p.start()
  File "/home/zio/mocap/MMNet/processor/processor.py", line 127, in start
    self.test()
  File "/home/zio/mocap/MMNet/processor/recognition_rgb_fused.py", line 241, in test
    self.show_topk(k, 'eval')
  File "/home/zio/mocap/MMNet/processor/recognition_rgb_fused.py", line 123, in show_topk
    _, r11_yan = r1_yan[i]
IndexError: list index out of range
```

this is the code below
```
print('label: ', len(self.label)) # 수정
            for i,l in enumerate(self.label):
                #_, l = label[i]
                #_, r11 = r1[i]
                #_, r22 = r2[i]
                _, r33 = r3[i]
                _, r11_yan = r1_yan[i]
                _, r22_yan = r2_yan[i]
                #r = r11 + r22 + r33
```
could you let me know why the length of label and r1_yan are different and how to fix it?

Thank you!

**Comment by bruceyo** [comment]
I do not know how you prepare the training data. 16487 should be the correct one. Maybe you missed the [samples_with_missing_skeletons.txt](https://github.com/bruceyo/MMNet/blob/main/resource/NTU-RGB-D/samples_with_missing_skeletons.txt).

**Comment by zihos** [comment]
Thank you! I missed processing the missing data!

Thank you so much! :)

**Comment by katahiyu** [comment]
> Thank you! I missed processing the missing data!
> 
> Thank you so much! :)

Have you made good progress with your RGB video training since then?
I would like to know how you solved the problem as I am facing the same issue.

**Comment by neverstoplearn** [comment]
> The function in `MMnet/net/gcn.py` is to extract the joint weight feature from the GCN model. You might have not loaded the correct pre-trained GCN model of the skeleton modality.
> 
> Anyways, the information is not sufficient for tracing or reproducing the problem. You should provide more information such as how is your `train_rgb_fused.yaml` looks like.

i don not think it was load the false pre-trained GCN model, when I train the ntu joint GCN model，I got the same error, but the is same with the raw code of st-gcn,what's wrong with it? and I can not find the main_joint.py or main_bone.py?
